### ISSUE TITLE
Error caused in Gradle Build Toolts 2.0.0

### ISSUE THREAD

**Issue by fh127** [JakeWharton/sdk-manager-plugin#114]
HI, I have a problem with the sdk-manager-plugin, when the Android Studio upgrade in 2.0, the Gradle build tools update in 2.0.0, too, and in an Android project, I have the next error:

    Error:Cause: com.android.sdklib.repository.FullRevision

**Comment by fh127** [comment]
HI, I have a problem with the sdk-manager-plugin, when the Android Studio upgrade in 2.0, the Gradle build tools update in 2.0.0, and Android project, I have the next error:

     Error:Cause: com.android.sdklib.repository.FullRevision

**Comment by JakeWharton** [comment]
Dupe #99
