### ISSUE TITLE
Please release new version with fixed problem with Android Gradle plugin 2.0

### ISSUE THREAD

**Issue by Malachiasz** [JakeWharton/sdk-manager-plugin#117]
The problem described here is fixed: https://github.com/JakeWharton/sdk-manager-plugin/pull/100 https://github.com/JakeWharton/sdk-manager-plugin/issues/99

But people have to use sdk manager from 3rd party repositories or build sources themself:
http://stackoverflow.com/a/33882513/2075875

Why don't you release a new version in your current repository?

**Comment by JakeWharton** [comment]
Because I'm not prepared to maintain it
