### ISSUE TITLE
Is this project deprecated?

### ISSUE THREAD

**Issue by adi1133** [JakeWharton/sdk-manager-plugin#118]
Last release is more than two years ago, also the last release isn't compatible with the current android gradle plugin (2.1)

Is this project deprecated? If it is what other similar projects do you use in your CI build ?

**Comment by JesusM** [comment]
> also the last release isn't compatible with the current android gradle plugin (2.1)

Take a look to https://github.com/JakeWharton/sdk-manager-plugin/issues/73#issuecomment-106747867 , you can use this plugin through jitpack .

**Comment by dalewking** [comment]
According to the Readme it is

**Comment by adi1133** [comment]
Mission Completed 👍
