### ISSUE TITLE
link for alternative?

### ISSUE THREAD

**Issue by davidmoten** [JakeWharton/sdk-manager-plugin#121]
Hi Jake
>This plugin is deprecated and is no longer being developed. The Android tools team has committed to automatically downloading tools and dependencies in v2.2.0 and will be improving it in subsequent releases.

I'm an irregular visitor to the android world but I haven't found anything about auto downloading sdks and 2.2.0. Can you provide a link that describes the alternative to your project please (and prehaps update the README with it)?
Thanks

**Comment by JakeWharton** [comment]
I quickly looked for a link but couldn't find one. 2.2 has just entered
beta so it's likely they don't have comprehensive documentation for the
feature yet. I'll keep an eye out and update as soon as I find one.

**Comment by FabianFrank** [comment]
You can also consider using https://github.com/tadfisher/android-sdk-updater in the meantime.

**Comment by vkotovv** [comment]
@davidmoten @JakeWharton until it is not released, one can look for instructions on [SO](http://stackoverflow.com/questions/38053578/how-to-set-up-automatic-google-support-repository-update-for-android-project).

**Comment by renaudboulard** [comment]
The Android Tools Team work on it, this is available since `2.2.0-alpha4 (2016/6/23)`, last version is in beta stage `2.2.0-beta2 (2016/8/19)` 

http://tools.android.com/tech-docs/new-build-system
> SDK auto-download: Gradle will attempt to download missing SDK packages that a project depends on.

At this stage this is not fully functional
https://code.google.com/p/android/issues/detail?id=212309
But a team member, has set this feature as :
> Priority=High since we're deprecating other paths to obtain this functionality.

**Comment by Erfa** [comment]
Hm... 2.2.0 seems to have been released on 2016-09-19, is it supposed work out of the box now? It still complains to me that it can't find the SDK without this plugin.

**Comment by JakeWharton** [comment]
https://developer.android.com/studio/intro/update.html#download-with-gradle
