### ISSUE TITLE
espresso-2.0 and testing-support-lib are not picked up as support library dependencies

### ISSUE THREAD

**Issue by marcin-kozinski** [JakeWharton/sdk-manager-plugin#63]
I'm not sure if that's this plugin's fault or Google's for naming choices. Anyway, the newly added testing libraries in support repository, like `espresso-2.0` and `testing-support-lib`, are not picked up by the plugin as part of the support library dependencies.

In my case it makes builds on my CI server to fail after switching to the new `AndroidJUnitRunner`, because plugin decides there are no missing dependencies from support repository and doesn't refresh it, but Gradle later fails because it can't find `com.android.support.test:testing-support-lib:0.1`.

The problem is of course those new dependencies use group `com.android.support.test` instead of just `com.android.support`. It could be fixed in the plugin by looking for dependencies with group starting with `com.android.support` or by whitelisting `com.android.support.test` as second accepted group. However, I don't have an opinion on which of the two (if any) is the correct course of action.

**Comment by brennantaylor** [comment]
:+1:

**Comment by brennantaylor** [comment]
Looks like some of the new google play services 6.5 components are not handled either if you just pull in maps for instance.

**Comment by Nkzn** [comment]
:+1:  I have same problem.

**Comment by blundell** [comment]
:+1:
