### ISSUE TITLE
support library resolution doesn't work in 0.12.0

### ISSUE THREAD

**Issue by sjamesr** [JakeWharton/sdk-manager-plugin#79]
I stumbled on a bug that is fixed by 13a66a192f84910f5679a8231360b931af0fb100, but that change is not in a release yet. Is there a plan to make a new release in the short term? It seems like an important fix!

**Comment by plastiv** [comment]
That's a known issue already. See solution here:
https://github.com/JakeWharton/sdk-manager-plugin/issues/73#issuecomment-106747867

**Comment by sjamesr** [comment]
JitPack is not an option for us, but at least there's another bug requesting a new release.
